/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-09-30 08:03:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class AddStudent_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- filepath: g:\\java project task\\student management systems\\Student management systems\\src\\main\\webapp\\AddStudent.jsp -->\r\n");
      out.write("\r\n");

    String adminUser = (String) session.getAttribute("adminUser");
    if (adminUser == null) {
        response.sendRedirect("AdminLogin.jsp");
        return;
    }

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Add Student - Student Management System</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            padding: 20px 0;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeInUp {\r\n");
      out.write("            from { opacity: 0; transform: translateY(50px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideInFromLeft {\r\n");
      out.write("            from { opacity: 0; transform: translateX(-50px); }\r\n");
      out.write("            to { opacity: 1; transform: translateX(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes pulse {\r\n");
      out.write("            0%, 100% { transform: scale(1); }\r\n");
      out.write("            50% { transform: scale(1.02); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border-radius: 15px;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            margin-bottom: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            color: white;\r\n");
      out.write("            animation: fadeInUp 0.8s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .header h1 {\r\n");
      out.write("            font-size: 2.5rem;\r\n");
      out.write("            font-weight: 700;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            text-shadow: 2px 2px 4px rgba(0,0,0,0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-card {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            animation: fadeInUp 1s ease-out;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .main-card::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-header {\r\n");
      out.write("            background: linear-gradient(135deg, #f8f9fa, #e9ecef);\r\n");
      out.write("            padding: 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-bottom: 1px solid #dee2e6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-header h2 {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            animation: slideInFromLeft 1.2s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .card-header .icon {\r\n");
      out.write("            font-size: 3rem;\r\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            margin-bottom: 15px;\r\n");
      out.write("            animation: pulse 2s infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-container {\r\n");
      out.write("            padding: 40px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            animation: fadeInUp 1.4s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-label i {\r\n");
      out.write("            color: #667eea;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control, .form-select {\r\n");
      out.write("            border: 2px solid #e9ecef;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control:focus, .form-select:focus {\r\n");
      out.write("            border-color: #667eea;\r\n");
      out.write("            box-shadow: 0 0 0 0.2rem rgba(102, 126, 234, 0.25);\r\n");
      out.write("            background: white;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-container {\r\n");
      out.write("            display: flex;\r\n");
      out.write("            gap: 15px;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            flex-wrap: wrap;\r\n");
      out.write("            margin-top: 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-custom {\r\n");
      out.write("            padding: 12px 30px;\r\n");
      out.write("            border-radius: 50px;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            border: none;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            min-width: 150px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-primary-custom {\r\n");
      out.write("            background: linear-gradient(135deg, #667eea, #764ba2);\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(102, 126, 234, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-secondary-custom {\r\n");
      out.write("            background: linear-gradient(135deg, #6c757d, #495057);\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(108, 117, 125, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-back-custom {\r\n");
      out.write("            background: linear-gradient(135deg, #28a745, #20c997);\r\n");
      out.write("            color: white;\r\n");
      out.write("            box-shadow: 0 4px 15px rgba(40, 167, 69, 0.3);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-custom:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .breadcrumb-nav {\r\n");
      out.write("            background: rgba(255, 255, 255, 0.1);\r\n");
      out.write("            backdrop-filter: blur(10px);\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 15px 25px;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            animation: slideInFromLeft 1s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .breadcrumb-nav a {\r\n");
      out.write("            color: white;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .breadcrumb-nav a:hover {\r\n");
      out.write("            color: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-custom {\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            animation: fadeInUp 0.6s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-success-custom {\r\n");
      out.write("            background: linear-gradient(135deg, #d4edda, #c3e6cb);\r\n");
      out.write("            color: #155724;\r\n");
      out.write("            border-left: 4px solid #28a745;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-danger-custom {\r\n");
      out.write("            background: linear-gradient(135deg, #f8d7da, #f5c6cb);\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("            border-left: 4px solid #dc3545;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 768px) {\r\n");
      out.write("            .form-container {\r\n");
      out.write("                padding: 25px;\r\n");
      out.write("            }\r\n");
      out.write("            .btn-container {\r\n");
      out.write("                flex-direction: column;\r\n");
      out.write("                align-items: center;\r\n");
      out.write("            }\r\n");
      out.write("            .btn-custom {\r\n");
      out.write("                width: 100%;\r\n");
      out.write("                max-width: 250px;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1><i class=\"fas fa-user-graduate\"></i> Student Management</h1>\r\n");
      out.write("            <p class=\"subtitle\">Add new student to the system</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <nav class=\"breadcrumb-nav\">\r\n");
      out.write("            <a href=\"index.html\"><i class=\"fas fa-home\"></i> Dashboard</a>\r\n");
      out.write("            <span class=\"mx-2 text-white-50\">â¢</span>\r\n");
      out.write("            <a href=\"AdminDashboard.jsp\"><i class=\"fas fa-tachometer-alt\"></i> Admin Dashboard</a>\r\n");
      out.write("            <span class=\"mx-2 text-white-50\">â¢</span>\r\n");
      out.write("            <span class=\"text-white\">Add Student</span>\r\n");
      out.write("        </nav>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"main-card\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("                <div class=\"icon\">\r\n");
      out.write("                    <i class=\"fas fa-user-plus\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("                <h2>Add New Student</h2>\r\n");
      out.write("                <p class=\"text-muted mb-0\">Please fill in all the required information</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"form-container\">\r\n");
      out.write("                ");
 if (request.getParameter("success") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert-custom alert-success-custom\">\r\n");
      out.write("                        <i class=\"fas fa-check-circle me-2\"></i>\r\n");
      out.write("                        Student added successfully!\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("                \r\n");
      out.write("                ");
 if (request.getParameter("error") != null) { 
      out.write("\r\n");
      out.write("                    <div class=\"alert-custom alert-danger-custom\">\r\n");
      out.write("                        <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
      out.write("                        Error adding student. Please try again.\r\n");
      out.write("                    </div>\r\n");
      out.write("                ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("                <form action=\"AddStudent\" method=\"post\" id=\"studentForm\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-user\"></i>\r\n");
      out.write("                                    Full Name\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"text\" name=\"name\" class=\"form-control\" \r\n");
      out.write("                                       placeholder=\"Enter full name\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-envelope\"></i>\r\n");
      out.write("                                    Email Address\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"email\" name=\"email\" class=\"form-control\" \r\n");
      out.write("                                       placeholder=\"Enter email address\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-birthday-cake\"></i>\r\n");
      out.write("                                    Age\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"number\" name=\"age\" class=\"form-control\" \r\n");
      out.write("                                       placeholder=\"Enter age\" min=\"16\" max=\"50\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-venus-mars\"></i>\r\n");
      out.write("                                    Gender\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <select name=\"gender\" class=\"form-select\" required>\r\n");
      out.write("                                    <option value=\"\">Select Gender</option>\r\n");
      out.write("                                    <option value=\"Male\">Male</option>\r\n");
      out.write("                                    <option value=\"Female\">Female</option>\r\n");
      out.write("                                    <option value=\"Other\">Other</option>\r\n");
      out.write("                                </select>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-graduation-cap\"></i>\r\n");
      out.write("                                    Course\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"text\" name=\"course\" class=\"form-control\" \r\n");
      out.write("                                       placeholder=\"Enter course\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-6\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-phone\"></i>\r\n");
      out.write("                                    Phone Number\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <input type=\"tel\" name=\"phone\" class=\"form-control\" \r\n");
      out.write("                                       placeholder=\"Enter phone number\" required>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-12\">\r\n");
      out.write("                            <div class=\"form-group\">\r\n");
      out.write("                                <label class=\"form-label\">\r\n");
      out.write("                                    <i class=\"fas fa-map-marker-alt\"></i>\r\n");
      out.write("                                    Address\r\n");
      out.write("                                </label>\r\n");
      out.write("                                <textarea name=\"address\" class=\"form-control\" rows=\"3\" \r\n");
      out.write("                                          placeholder=\"Enter complete address\" required></textarea>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"btn-container\">\r\n");
      out.write("                        <button type=\"submit\" class=\"btn-custom btn-primary-custom\">\r\n");
      out.write("                            <i class=\"fas fa-save me-2\"></i>Save Student\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <button type=\"reset\" class=\"btn-custom btn-secondary-custom\">\r\n");
      out.write("                            <i class=\"fas fa-undo me-2\"></i>Reset Form\r\n");
      out.write("                        </button>\r\n");
      out.write("                        <a href=\"AdminDashboard.jsp\" class=\"btn-custom btn-back-custom\">\r\n");
      out.write("                            <i class=\"fas fa-arrow-left me-2\"></i>Back to Dashboard\r\n");
      out.write("                        </a>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script>\r\n");
      out.write("        // Form validation and enhancements\r\n");
      out.write("        const form = document.getElementById('studentForm');\r\n");
      out.write("        const inputs = form.querySelectorAll('input, select, textarea');\r\n");
      out.write("\r\n");
      out.write("        inputs.forEach(input => {\r\n");
      out.write("            input.addEventListener('input', function() {\r\n");
      out.write("                validateField(this);\r\n");
      out.write("            });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        function validateField(field) {\r\n");
      out.write("            const isValid = field.checkValidity();\r\n");
      out.write("            \r\n");
      out.write("            if (isValid) {\r\n");
      out.write("                field.classList.remove('is-invalid');\r\n");
      out.write("                field.classList.add('is-valid');\r\n");
      out.write("            } else {\r\n");
      out.write("                field.classList.remove('is-valid');\r\n");
      out.write("                field.classList.add('is-invalid');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Auto-hide alerts\r\n");
      out.write("        const alerts = document.querySelectorAll('.alert-custom');\r\n");
      out.write("        alerts.forEach(alert => {\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                alert.style.opacity = '0';\r\n");
      out.write("                setTimeout(() => alert.remove(), 300);\r\n");
      out.write("            }, 5000);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
