/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.41
 * Generated at: 2025-09-30 07:39:37 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class FacultyLogin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- filepath: g:\\java project task\\student management systems\\Student management systems\\src\\main\\webapp\\FacultyLogin.jsp -->\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Faculty Login - Student Management System</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <style>\r\n");
      out.write("        * {\r\n");
      out.write("            margin: 0;\r\n");
      out.write("            padding: 0;\r\n");
      out.write("            box-sizing: border-box;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        body {\r\n");
      out.write("            font-family: 'Poppins', sans-serif;\r\n");
      out.write("            background: linear-gradient(135deg, #4ecdc4 0%, #44a08d 100%);\r\n");
      out.write("            min-height: 100vh;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            justify-content: center;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes fadeInUp {\r\n");
      out.write("            from { opacity: 0; transform: translateY(50px); }\r\n");
      out.write("            to { opacity: 1; transform: translateY(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes slideInFromLeft {\r\n");
      out.write("            from { opacity: 0; transform: translateX(-50px); }\r\n");
      out.write("            to { opacity: 1; transform: translateX(0); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @keyframes float {\r\n");
      out.write("            0%, 100% { transform: translateY(0px); }\r\n");
      out.write("            50% { transform: translateY(-10px); }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-container {\r\n");
      out.write("            background: white;\r\n");
      out.write("            border-radius: 20px;\r\n");
      out.write("            box-shadow: 0 20px 40px rgba(0, 0, 0, 0.1);\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            max-width: 450px;\r\n");
      out.write("            animation: fadeInUp 1s ease-out;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-container::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 0;\r\n");
      out.write("            left: 0;\r\n");
      out.write("            right: 0;\r\n");
      out.write("            height: 4px;\r\n");
      out.write("            background: linear-gradient(135deg, #4ecdc4, #44a08d);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-header {\r\n");
      out.write("            background: linear-gradient(135deg, #f8f9fa, #e9ecef);\r\n");
      out.write("            padding: 40px 30px 30px;\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            border-bottom: 1px solid #dee2e6;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-icon {\r\n");
      out.write("            font-size: 4rem;\r\n");
      out.write("            background: linear-gradient(135deg, #4ecdc4, #44a08d);\r\n");
      out.write("            -webkit-background-clip: text;\r\n");
      out.write("            -webkit-text-fill-color: transparent;\r\n");
      out.write("            margin-bottom: 20px;\r\n");
      out.write("            animation: float 3s ease-in-out infinite;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-title {\r\n");
      out.write("            color: #333;\r\n");
      out.write("            font-size: 2rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            margin-bottom: 10px;\r\n");
      out.write("            animation: slideInFromLeft 1.2s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-subtitle {\r\n");
      out.write("            color: #666;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            animation: slideInFromLeft 1.4s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .login-body {\r\n");
      out.write("            padding: 40px 30px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-group {\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            position: relative;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-label {\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            color: #333;\r\n");
      out.write("            margin-bottom: 8px;\r\n");
      out.write("            display: flex;\r\n");
      out.write("            align-items: center;\r\n");
      out.write("            gap: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-label i {\r\n");
      out.write("            color: #4ecdc4;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control {\r\n");
      out.write("            border: 2px solid #e9ecef;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 12px 16px;\r\n");
      out.write("            font-size: 1rem;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            background: #f8f9fa;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .form-control:focus {\r\n");
      out.write("            border-color: #4ecdc4;\r\n");
      out.write("            box-shadow: 0 0 0 0.2rem rgba(78, 205, 196, 0.25);\r\n");
      out.write("            background: white;\r\n");
      out.write("            transform: translateY(-2px);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .password-toggle {\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            right: 15px;\r\n");
      out.write("            top: 38px;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            color: #666;\r\n");
      out.write("            transition: color 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .password-toggle:hover {\r\n");
      out.write("            color: #4ecdc4;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login {\r\n");
      out.write("            width: 100%;\r\n");
      out.write("            padding: 12px;\r\n");
      out.write("            background: linear-gradient(135deg, #4ecdc4, #44a08d);\r\n");
      out.write("            color: white;\r\n");
      out.write("            border: none;\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            font-size: 1.1rem;\r\n");
      out.write("            font-weight: 600;\r\n");
      out.write("            cursor: pointer;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("            position: relative;\r\n");
      out.write("            overflow: hidden;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login::before {\r\n");
      out.write("            content: '';\r\n");
      out.write("            position: absolute;\r\n");
      out.write("            top: 50%;\r\n");
      out.write("            left: 50%;\r\n");
      out.write("            width: 0;\r\n");
      out.write("            height: 0;\r\n");
      out.write("            background: rgba(255, 255, 255, 0.2);\r\n");
      out.write("            border-radius: 50%;\r\n");
      out.write("            transition: all 0.4s ease;\r\n");
      out.write("            transform: translate(-50%, -50%);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login:hover::before {\r\n");
      out.write("            width: 300px;\r\n");
      out.write("            height: 300px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .btn-login:hover {\r\n");
      out.write("            transform: translateY(-3px);\r\n");
      out.write("            box-shadow: 0 8px 25px rgba(78, 205, 196, 0.4);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link {\r\n");
      out.write("            text-align: center;\r\n");
      out.write("            margin-top: 20px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link a {\r\n");
      out.write("            color: #4ecdc4;\r\n");
      out.write("            text-decoration: none;\r\n");
      out.write("            font-weight: 500;\r\n");
      out.write("            transition: all 0.3s ease;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .back-link a:hover {\r\n");
      out.write("            color: #44a08d;\r\n");
      out.write("            text-shadow: 0 2px 4px rgba(0,0,0,0.1);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-custom {\r\n");
      out.write("            border-radius: 12px;\r\n");
      out.write("            padding: 15px 20px;\r\n");
      out.write("            margin-bottom: 25px;\r\n");
      out.write("            border: none;\r\n");
      out.write("            animation: fadeInUp 0.6s ease-out;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .alert-danger-custom {\r\n");
      out.write("            background: linear-gradient(135deg, #f8d7da, #f5c6cb);\r\n");
      out.write("            color: #721c24;\r\n");
      out.write("            border-left: 4px solid #dc3545;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        @media (max-width: 576px) {\r\n");
      out.write("            .login-header {\r\n");
      out.write("                padding: 30px 20px 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .login-body {\r\n");
      out.write("                padding: 30px 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .login-title {\r\n");
      out.write("                font-size: 1.5rem;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"login-container\">\r\n");
      out.write("        <div class=\"login-header\">\r\n");
      out.write("            <div class=\"login-icon\">\r\n");
      out.write("                <i class=\"fas fa-chalkboard-teacher\"></i>\r\n");
      out.write("            </div>\r\n");
      out.write("            <h2 class=\"login-title\">Faculty Login</h2>\r\n");
      out.write("            <p class=\"login-subtitle\">Welcome back! Please sign in to continue</p>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"login-body\">\r\n");
      out.write("            ");
 if (request.getParameter("error") != null) { 
      out.write("\r\n");
      out.write("                <div class=\"alert-custom alert-danger-custom\">\r\n");
      out.write("                    <i class=\"fas fa-exclamation-circle me-2\"></i>\r\n");
      out.write("                    Invalid credentials. Please try again.\r\n");
      out.write("                </div>\r\n");
      out.write("            ");
 } 
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <form action=\"FacultyLogin\" method=\"post\" id=\"loginForm\">\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\">\r\n");
      out.write("                        <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        Username\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input type=\"text\" name=\"username\" class=\"form-control\" \r\n");
      out.write("                           placeholder=\"Enter your username\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <div class=\"form-group\">\r\n");
      out.write("                    <label class=\"form-label\">\r\n");
      out.write("                        <i class=\"fas fa-lock\"></i>\r\n");
      out.write("                        Password\r\n");
      out.write("                    </label>\r\n");
      out.write("                    <input type=\"password\" name=\"password\" class=\"form-control\" \r\n");
      out.write("                           placeholder=\"Enter your password\" required id=\"passwordField\">\r\n");
      out.write("                    <i class=\"fas fa-eye password-toggle\" onclick=\"togglePassword()\"></i>\r\n");
      out.write("                </div>\r\n");
      out.write("\r\n");
      out.write("                <button type=\"submit\" class=\"btn-login\">\r\n");
      out.write("                    <i class=\"fas fa-sign-in-alt me-2\"></i>Sign In\r\n");
      out.write("                </button>\r\n");
      out.write("            </form>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"back-link\">\r\n");
      out.write("                <a href=\"index.html\">\r\n");
      out.write("                    <i class=\"fas fa-arrow-left me-1\"></i>\r\n");
      out.write("                    Back to Dashboard\r\n");
      out.write("                </a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <script>\r\n");
      out.write("        function togglePassword() {\r\n");
      out.write("            const passwordField = document.getElementById('passwordField');\r\n");
      out.write("            const toggleIcon = document.querySelector('.password-toggle');\r\n");
      out.write("            \r\n");
      out.write("            if (passwordField.type === 'password') {\r\n");
      out.write("                passwordField.type = 'text';\r\n");
      out.write("                toggleIcon.classList.remove('fa-eye');\r\n");
      out.write("                toggleIcon.classList.add('fa-eye-slash');\r\n");
      out.write("            } else {\r\n");
      out.write("                passwordField.type = 'password';\r\n");
      out.write("                toggleIcon.classList.remove('fa-eye-slash');\r\n");
      out.write("                toggleIcon.classList.add('fa-eye');\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        // Auto-hide error messages\r\n");
      out.write("        const alerts = document.querySelectorAll('.alert-custom');\r\n");
      out.write("        alerts.forEach(alert => {\r\n");
      out.write("            setTimeout(() => {\r\n");
      out.write("                alert.style.opacity = '0';\r\n");
      out.write("                setTimeout(() => alert.remove(), 300);\r\n");
      out.write("            }, 5000);\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
